### ISSUE TITLE
class Attribute not renamed in ManageReservationsPresenter.php

### ISSUE THREAD

**Issue by crckmc** [LibreBooking/app#101]
I tried setting up a new instance with the latest files from git and ran into this error:

2022-03-09T13:00:14+01:00 [1] ERROR default - [User=Admin Admin (admin@example.com)] Uncaught exception: Error: Class 'Attribute' not found in /hp/cu/aa/cd/www/ti/Presenters/Admin/ManageReservationsPresenter.php:175
Stack trace:
#0 /hp/cu/aa/cd/www/ti/Pages/Admin/ManageReservationsPage.php(371): ManageReservationsPresenter->PageLoad('Europe/Berlin')
#1 /hp/cu/aa/cd/www/ti/Pages/ActionPage.php(32): ManageReservationsPage->ProcessPageLoad()
#2 /hp/cu/aa/cd/www/ti/Pages/Admin/AdminPage.php(27): ActionPage->PageLoad()
#3 /hp/cu/aa/cd/www/ti/Web/admin/manage_reservations.php(9): AdminPageDecorator->PageLoad()
#4 {main} [File=/hp/cu/aa/cd/www/ti/lib/Common/Logging/ExceptionHandler.php,Line=19]

Turns out "ManageReservationsPresenter" still uses Attribute class instead of LBAttribute.

**Comment by JohnVillalovos** [comment]
Issue has been resolved.
