### ISSUE TITLE
Minimal Setup using XAMPP + Windows 10

### ISSUE THREAD

**Issue by nieuwefn** [LibreBooking/app#13]
Hey,

I've been trying to get this project running using XAMPP and a Windows 10 machine, following the readme_installation.

I unzipped the the distribution and moved in to the XAMPP doc root (htdocs). Copied the config.dist.php and renamed to config.php and made sure the web server has write access, which it already has in Win10. Session.autostart is disabled.

When looking at the config.php, it seems the only thing I might need to change initially is the script.url, which I've done.
As I'm using XAMPP I created the DB using phpMyAdmin and then imported the full-install.sql which worked.
I've tried many variations, but no matter what I attempt, when opening the application in localhost, I always get errors as seen in the image below. (Note these errors also came before the database 'bookedscheduler' has even been created and filled out)
![image](https://user-images.githubusercontent.com/17641062/110107856-bb49fd00-7dab-11eb-9e50-444abff52577.png)

Is this a common error? Couldn't find anything along those lines in the Community Support Forum or in other Issues here.
Can anyone else reproduce this?
I'd like to use this Issue to later help other users in getting an easy initial setup running.

Greetings

**Comment by nieuwefn** [comment]
I can give you more precice information later, but it was the latest XAMPP version, so it either contained PHP 8.0.2 or 7.4.15.
Can you give me a quick summary of the steps you performed to install the scheduler, so I can attempt to reproduce it tonight?

**Comment by effgarces** [comment]
I've installed  it using two methods, just to check. For both I created a new database called booked

1.  Using the web installer
 Created a booked folder on htdocs and extracted the latest maintenance release there
 Duplicated the config-dist.php file and renamed it to config.php
 Edited config.php with the correct url (http://localhost/booked/Web)
 Went to http://localhost/booked/Web/install and followed the steps 
 There were some sql errors, that seem to be related to upgrading from previous versions, but at the end the installation was working fine
  
2.  Importing the full-install.sql and the sample data sql
 Created a booked folder on htdocs and extracted the latest maintenance release there
 Duplicated the config-dist.php file and renamed it to config.php
 Edited config.php with the correct url (http://localhost/booked/Web) and the correct database (name: booked, user: root, no password)
 Using phpmyadmin I imported the full-install.sql onto the "booked" database, I also imported the sample data
 Afterwards accessed http://localhost/booked/Web and all seemed well
 I did not encountered any errors using this method.

**Comment by nieuwefn** [comment]
Okay, I'm quite sure, I attempted both methods you described above at some point in time. Following your first instructions using XAMPP 7.4 is now working though, so thanks a bunch.
If you want I can extend the readme soon including some basic instructions like you described above? I'll troubleshoot some more over the weekend, but I believe XAMPP 8.x must be causing some problems with the installation.

**Comment by jyotisankar** [comment]
I've tried to setup booked using XAMPP 7.4 (https://www.apachefriends.org/xampp-files/7.4.16/xampp-windows-x64-7.4.16-0-VC15-installer.exe) multiple times using both methods shared by  effgarces. However I can't get it get it working at all, it always shows Unknow Error. I've no clue what am I doing differenet or wrong, any help is appriciated.

**Comment by effgarces** [comment]
Do you have any logs that might help pinpoint what is causing this issue? Namely the error.log should be usefull.

**Comment by jyotisankar** [comment]
This is what I see in the log, when accessing, http://localhost/booked/web/ 

2021-04-23T05:23:59+02:00 [16452] ERROR default - [User=  ()] Error connecting to database
Check your database settings in the config file
 [File=C:\xampp\htdocs\booked\lib\Database\MySQL\MySqlConnection.php,Line=67]
2021-04-23T05:23:59+02:00 [16452] ERROR default - [User=  ()] Uncaught exception: Exception: Error connecting to database
Error:  in C:\xampp\htdocs\booked\lib\Database\MySQL\MySqlConnection.php:68
Stack trace:
#0 C:\xampp\htdocs\booked\lib\Database\Database.php(41): MySqlConnection->Connect()
#1 C:\xampp\htdocs\booked\Domain\Access\AnnouncementRepository.php(29): Database->Query(Object(GetDashboardAnnouncementsCommand))
#2 C:\xampp\htdocs\booked\Presenters\LoginPresenter.php(154): AnnouncementRepository->GetFuture(5)
#3 C:\xampp\htdocs\booked\Pages\LoginPage.php(138): LoginPresenter->PageLoad()
#4 C:\xampp\htdocs\booked\Web\index.php(43): LoginPage->PageLoad()
#5 {main} [File=C:\xampp\htdocs\booked\lib\Common\Logging\ExceptionHandler.php,Line=33]

**Comment by effgarces** [comment]
Those errors indicate a problem connecting to the MySQL server,  can you confirm that the config.php is correctly setup?

**Comment by jyotisankar** [comment]
Yeah, I modified the config.php file as per instructions.

**Comment by effgarces** [comment]
Have you tried to do a manual install? Using phpmyadmin create a new DB `booked`, import `full-install.sql` onto to it, afterwards import `sample-data-utf8.sql` for the sample data (default password for `admin` and `user` is `password`).
Next you just need to edit config.php to suit your environment, (I've attached my config.php so that you can see if there is any difference [config.zip](https://github.com/effgarces/BookedScheduler/files/6375443/config.zip) )

**Comment by jyotisankar** [comment]
There was not any difference in config file.

**Comment by Aender1** [comment]
Hey guys. I'm having the same problem. I need to configure the booked scheduler in local environment, using XAMPP + Windows 10, but I can never get to the installation screen. The steps I'm doing are the following:

- Install XAMPP (latest version)
- Download the booked scheduler ( version ( 2.8.5)
- Extract the compressed contents of the booked scheduler in the XAMPP htdocs folder
- Look for the config-dist.php file in the config folder and rename it to config.php
- Open config.php and change the parameter ['script.url'] to = 'http://localhost/booked/Web';
- Type in the browser http://localhost/booked/Web/install to start the automatic configuration screen.

But after following all these steps comes the following problem:

"Warning: Undefined array key "Validator" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 119

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 119

Warning: Undefined array key "InlineEdit" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 124

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 124

Warning: Undefined array key "Select2" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 132

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 132

Warning: Undefined array key "Timepicker" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 136

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 136

Warning: Undefined array key "Fullcalendar" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 140

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 140

Warning: Undefined array key "Owl" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 146

Warning: Attempt to read property "value" on null in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 146

Warning: Undefined array key "cssFiles" in C:\xampp\htdocs\booked\tpl_c\765c71a6c4d9e3fb9a18656cd344c3dfc6830da9_0.file.globalheader.tpl.php on line 159
"

I no longer know how to proceed, it seems that I am doing it right, but the problem always occurs. Thank you guys for the help.

**Comment by treborin** [comment]
PHP versio? , @Aender1

**Comment by treborin** [comment]
> > PHP version? , @Aender1
> 
> Thanks.  
> PHP versions 8.2.4 . XAMPP (latest version).

That's the issue, @Aender1 . Master branch is ready for PHP7.4.
There is a develop branch that should work with PHP8.1, but not sure for 8.2

**Comment by Aender1** [comment]
> > > PHP version? , @Aender1
> > 
> > 
> > Thanks.
> > PHP versions 8.2.4 . XAMPP (latest version).
> 
> That's the issue, @Aender1 . Master branch is ready for PHP7.4. There is a develop branch that should work with PHP8.1, but not sure for 8.2

That might be the problem. In the installation requirements is PHP 8.0, 8.1
 with PHP 8.1 recommended. I'm going to install a previous version of XAMPP to test. Thank you for the tip. Hugs

**Comment by Aender1** [comment]
[treborin](https://github.com/treborin)  
Would you describe the steps you are using to install? Thanks.

**Comment by Aender1** [comment]
[treborin](https://github.com/treborin)  

OK , I'll try with PHP 7.1. Thank you very much.

**Comment by Aender1** [comment]
> > > > PHP version? , @Aender1
> > > 
> > > 
> > > Thanks.
> > > PHP versions 8.2.4 . XAMPP (latest version).
> > 
> > 
> > That's the issue, @Aender1 . Master branch is ready for PHP7.4. There is a develop branch that should work with PHP8.1, but not sure for 8.2
> 
> As i told you, you need to use PHP 7.4 for the master stable branch. For PHP 8.1, use develop branch And i see that all these warnings comes from tpl_c cache folder. You should empty that folder

Thank you so much for your help, I was finally able to move forward with the installation using PHP 7.4 as you suggested, but I still can't finish the setup. When accessing the localhost/booked/Web/install address, I am directed to the initial configuration screen, but a Warning error appears.

![booked2](https://user-images.githubusercontent.com/54954024/232134639-5b8d793d-fabe-4341-b1d7-9c13eb853c76.jpg)

Even so, I proceed with the installation and other errors are returned, which are described in the attached PDF file.
[bookedpdf.pdf](https://github.com/LibreBooking/app/files/11236361/bookedpdf.pdf)

I'm still at the beginning with SQL and I really don't know how to solve this. If you can still help me I will be very grateful.

**Comment by Aender1** [comment]
Finally I managed to solve the Warning problem leaving the following configuration for the database in config.php;

 database configuration
 */
$conf['settings']['database']['type'] = 'mysql';
$conf['settings']['database']['user'] = 'root'; // database user with permission to the booked database
$conf['settings']['database']['password'] = '';
$conf['settings']['database']['hostspec'] = '127.0.0.1'; // ip, dns or named pipe
$conf['settings']['database']['name'] = 'booked';

Now everything is up and running : Booked Booked Scheduler v2.8.5 + PHP 7.4 .

Thank you all for your help.

**Comment by JohnVillalovos** [comment]
This issue seems stale. Closing. Feel free to reopen if desired.
