### ISSUE TITLE
Cannot rename resources

### ISSUE THREAD

**Issue by lukebarone** [LibreBooking/app#148]
Updated as of this morning to version 2.8.5.5, using MariaDB hosted on the same server.

## Steps to reproduce

1. Application Management -> Resources
2. Click to rename a resource. Type the new name and hit the check box.
3. Refresh the page. The name is still the same. Uncaught exception appears in log:

```log
2022-11-02T09:02:41-07:00 [289208] ERROR default - [User=Luke Barone (tech@example.com)] ProcessAction Error. Action rename, Error Exception: There was an error executing your query\nUnknown column 'additional_properties' in 'field list' in /var/www/BookedScheduler/lib/Database/MySQL/MySqlConnection.php:114
Stack trace:
#0 /var/www/BookedScheduler/lib/Database/MySQL/MySqlConnection.php(101): MySqlConnection->_handleError()
#1 /var/www/BookedScheduler/lib/Database/Database.php(63): MySqlConnection->Execute()
#2 /var/www/BookedScheduler/Domain/Access/ResourceRepository.php(228): Database->Execute()
#3 /var/www/BookedScheduler/Presenters/Admin/ManageResourcesPresenter.php(346): ResourceRepository->Update()
#4 /var/www/BookedScheduler/Presenters/ActionPresenter.php(68): ManageResourcesPresenter->Rename()
#5 /var/www/BookedScheduler/Pages/Admin/ManageResourcesPage.php(563): ActionPresenter->ProcessAction()
#6 /var/www/BookedScheduler/Pages/ActionPage.php(27): ManageResourcesPage->ProcessAction()
#7 /var/www/BookedScheduler/Pages/Admin/AdminPage.php(27): ActionPage->PageLoad()
#8 /var/www/BookedScheduler/Web/admin/manage_resources.php(9): AdminPageDecorator->PageLoad()
#9 {main} [File=/var/www/BookedScheduler/Presenters/ActionPresenter.php,Line=71]
```

Looking in the database at the Resources table, I see these headers:

- resource_id 
- name           
- location 
- contact_info 
- description 
- notes 
- min_duration 
- min_increment 
- max_duration 
- unit_cost 
- autoassign 
- requires_approval 
- allow_multiday_reservations 
- max_participants 
- min_notice_time_add 
- max_notice_time 
- image_name 
- schedule_id 
- legacyid 
- admin_group_id 
- public_id 
- allow_calendar_subscription 
- sort_order 
- resource_type_id 
- status_id 
- resource_status_reason_id 
- buffer_time 
- enable_check_in 
- auto_release_minutes 
- color   
- allow_display 
- credit_count 
- peak_credit_count 
- min_notice_time_update 
- min_notice_time_delete 
- date_created        
- last_modified

**Comment by lukebarone** [comment]
Well I feel silly now... Apparently I missed that I have manual steps during upgrades. I ran `mysql booked < database_schema/upgrades/2.8/schema.sql` and it's working now.

So suggestion: when a database upgrade is needed, either to automatically apply them, or tell the admin user when they log in that upgrades are needed.
