### ISSUE TITLE
Reporting not working anymore

### ISSUE THREAD

**Issue by zed76** [LibreBooking/app#151]
my hosting provider switched to PHP 8.1, now Reporting is not working anymore.

The errors log reads 

`Stack trace:
#0 /is/htdocs/wp13484192_NWVLTH8V9S/www/test/lib/Application/Reporting/ReportDefinition.php(4): require_once()
#1 /is/htdocs/wp13484192_NWVLTH8V9S/www/test/lib/Application/Reporting/namespace.php(7): require_once('/is/htdocs/wp13...')
#2 /is/htdocs/wp13484192_NWVLTH8V9S/www/test/Presenters/Reports/CommonReportsPresenter.php(6): require_once('/is/htdocs/wp13...')
#3 /is/htdocs/wp13484192_NWVLTH8V9S/www/test/Pages/Reports/CommonReportsPage.php(5): require_once('/is/htdocs/wp13...')
#4 /is/htdocs/wp13484192_NWVLTH8V9S/www/test/Web/reports/common-reports.php(4): require_once('/is/htdocs/wp13...')
#5 {main} [File=/is/htdocs/wp13484192_NWVLTH8V9S/www/test/lib/Common/Logging/ExceptionHandler.php,Line=19]
2022-11-19T10:44:50+01:00 [32133] ERROR default - [User=Admin Admin (admin@example.com)] Uncaught exception: Error: Class "ReportCell" not found in /is/htdocs/wp13484192_NWVLTH8V9S/www/test/lib/Application/Reporting/ReportColumn.php:5`

Any ideas how to fix this or is this a problem specific to my hosting provider (Hosteurope)? I double checked this error by doing a fresh install.

**Comment by effgarces** [comment]
The problem is with librebooking and PHP8.1, not your hosting provider, I believe that it's the last thing still causing issues with php8, at the moment I still haven't managed to fix it and will probably only have time to dive again on to the code in a few weeks

**Comment by zed76** [comment]
thank you a lot for your effort to keep librebooking running. I will wait for a fix then 😊
