### ISSUE TITLE
still no luck with PHP 8.1. getting "unknown error" message

### ISSUE THREAD

**Issue by guilegatan** [LibreBooking/app#171]
Sorry to bring it up again. I am still out of luck with PHP 8.1.9/MySQL 8.0.32

I installed the latest development version, and also installed Composer as mentionend somewhere else.

These are my last log lines in the apache error.log:
`
[Fri Feb 10 09:20:22.790289 2023] [php:notice] [pid 966] [client 192.168.0.15:31342] Error: mysqli_sql_exception: Variable '
sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' in
/var/www/html/app-develop/lib/Database/MySQL/MySqlConnection.php:72\nStack trace:\n#0 /var/www/html/app-develop/lib/Database/MySQL/MySqlConnection.php(72): mysqli_query()\n#1 /var/www/html/app-develop/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/app-develop/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/app-develop/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/app-develop/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/app-develop/Web/index.php(25): LoginPage->PageLoad()\n#6 {main}, referer: https://testserver.my.url/app-develop/Web/index.php
[Fri Feb 10 09:20:22.790371 2023] [php:notice] [pid 966] [client 192.168.0.15:31342] #0 /var/www/html/app-develop/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(mysqli_sql_exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(mysqli_sql_exception))\n, referer: https://testserver.my.url/app-develop/Web/index.php
[Fri Feb 10 09:20:24.363937 2023] [php:notice] [pid 966] [client 192.168.0.15:31342] Error: mysqli_sql_exception: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' in /var/www/html/app-develop/lib/Database/MySQL/MySqlConnection.php:72\nStack trace:\n#0 /var/www/html/app-develop/lib/Database/MySQL/MySqlConnection.php(72): mysqli_query()\n#1 /var/www/html/app-develop/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/app-develop/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/app-develop/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/app-develop/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/app-develop/Web/index.php(25): LoginPage->PageLoad()\n#6 {main}, referer: https://testserver.my.url/app-develop/Web/index.php
[Fri Feb 10 09:20:24.363999 2023] [php:notice] [pid 966] [client 192.168.0.15:31342] #0 /var/www/html/app-develop/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(mysqli_sql_exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(mysqli_sql_exception))\n, referer: https://testserver.my.url/app-develop/Web/index.php
`

can anyone give me a hint how you got it working? I tried a clean Ubuntu 22.04 install with PHP 8.1.9 and MySQL 8.0.32, and imported my LibreBooking database from my Ubuntu 20.04/PHP 7.4.3/MySQL 8.0.32-server, but with no luck.

![Zwischenablage01](https://user-images.githubusercontent.com/16672201/218056758-766cb087-9836-40d2-b79b-c104b145af5f.jpg)

**Comment by cyberfarer** [comment]
I think you must use PHP 7.x. As soon as I switch to PHP8.1 I get the same error.

**Comment by effgarces** [comment]
PHP 8 should be working, due to the contribution of several people of the community, but unfortunaly at the moment I really don't have time to debug this particular matter, so from just reading the log, it looks like a MySQL problem, not PHP, and it seems to revolve around "sql_mode"

**Comment by jonnyforestGIS** [comment]
Probably related to this:
[https://stackoverflow.com/questions/50336378/variable-sql-mode-cant-be-set-to-the-value-of-no-auto-create-user](https://stackoverflow.com/questions/50336378/variable-sql-mode-cant-be-set-to-the-value-of-no-auto-create-user)

Cheers

**Comment by guilegatan** [comment]
Finally got it working with PHP 8.1 with some help from our database guys for the production machines!
Thanks everyone for the input! Looking forward to an official version 2.8.5.6.

**Comment by PVTGoesen** [comment]
Hi,
do you have an list of the changes you made?

**Comment by treborin** [comment]
Pls. check new PR: [https://github.com/LibreBooking/app/pull/198](url)

**Comment by TheHLee** [comment]
I confirmed the above error is showing because 'NO_AUTO_CREATE_USER' has been deprecated since MySQL 8.0.11. See the following link for more info:
https://stackoverflow.com/questions/71110454/no-auto-create-user-in-mysql-8-0

I removed NO_AUTO_CREATE_USER from MySqlConnection.php and that fixed the problem for me.

My environment:

- Ubuntu 22.04.1
- MySQL 8.0.34
- PHP 8.1.2
- LibreBooking v2.8.6 master branch

**Comment by colisee** [comment]
@hakito , 

did you try the solution that was given by @TheHLee on Sep 6 ?

**Comment by hakito** [comment]
Yes I tried it and the error was gone. But because I was unsure about other potential problems, I returned to an older MySQL Version.

**Comment by colisee** [comment]
@hakito, glad your problem is gone. Could you please close this issue?

**Comment by hakito** [comment]
@colisee I can't close it - I did not open the issue!

**Comment by reaseno** [comment]
There are two solutions/workarounds:

1. remove NO_AUTO_CREATE_USER from lib/Database/MySQL/MySqlConnection.php
2. add mysqli_report(MYSQLI_REPORT_OFF); to the config.php file, which is there by default

However, the line from the second option is removed when you edit the configuration in the admin menu (tested in v2.8.6.1). So the first solution is the better one.

 Thus, the issue should not be closed until this is fixed.
