### ISSUE TITLE
UnexpectedValueException Errors

### ISSUE THREAD

**Issue by RadioStars** [LibreBooking/app#221]
After updating LibreBooking from 2.8.4 to 2.8.6, I get an error page of 30+ lines starting with  UnexpectedValueException: The stream or file "/app.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: [User= ()]
When I go back a page, I find that I am logged in OK.
Once logged in, I also get similar error messages on the Schedule Bookings and Account Profile pages.
Any help on this issue would be very much appreciated.

**Comment by RadioStars** [comment]
I forgot to mention that the LibreBooking installation is within a Cpanel account and I don't have access to /app.log in the /var directory.

**Comment by wfGhgATv** [comment]
Hello everyone, and thanks for LibreBooking,

Coming back to the subject, I'm having the same problem with an upgrade from v2.8.5.5 (php 7.4 / MySQL 5.7) to v2.8.6.1 (php 8.1 or even 8.2 / MySQL 5.7) on **shared hosting**.

Here are the details of the message obtained after (each) login:

`UnexpectedValueException: There is no existing directory at "/var/log/librebooking/log" and it could not be created: Permission denied in /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:216 Stack trace: #0 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(135): Monolog\Handler\StreamHandler->createDir('/var/log/libreb...') #1 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array) #2 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(611): Monolog\Logger->addRecord(200, '[User= ()] Try...', Array) #4 /server_directory/website_folder/lib/Common/Logging/Log.php(82): Monolog\Logger->info('[User= ()] Try...') #5 /server_directory/website_folder/lib/Application/Authentication/Authentication.php(82): Log::Debug('Trying to log i...', Array) #6 /server_directory/website_folder/lib/Application/Authentication/WebAuthentication.php(96): Authentication->Validate('user@websit...', 'userPasswor...') #7 /server_directory/website_folder/Presenters/LoginPresenter.php(135): WebAuthentication->Validate('user@websit...', 'userPasswor...') #8 /server_directory/website_folder/Pages/LoginPage.php(210): LoginPresenter->Login() #9 /server_directory/website_folder/Web/index.php(15): LoginPage->Login() #10 {main}UnexpectedValueException: There is no existing directory at "/var/log/librebooking/log" and it could not be created: Permission denied in /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:216 Stack trace: #0 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(135): Monolog\Handler\StreamHandler->createDir('/var/log/libreb...') #1 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array) #2 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(611): Monolog\Logger->addRecord(200, '[User= ()] Use...', Array) #4 /server_directory/website_folder/lib/Common/Logging/Log.php(82): Monolog\Logger->info('[User= ()] Use...') #5 /server_directory/website_folder/lib/Application/Authentication/Authentication.php(89): Log::Debug('User was found:...', Array) #6 /server_directory/website_folder/lib/Application/Authentication/WebAuthentication.php(96): Authentication->Validate('user@websit...', 'userPasswor...') #7 /server_directory/website_folder/Presenters/LoginPresenter.php(135): WebAuthentication->Validate('user@websit...', 'userPasswor...') #8 /server_directory/website_folder/Pages/LoginPage.php(210): LoginPresenter->Login() #9 /server_directory/website_folder/Web/index.php(15): LoginPage->Login() #10 {main}UnexpectedValueException: There is no existing directory at "/var/log/librebooking/log" and it could not be created: Permission denied in /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:216 Stack trace: #0 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(135): Monolog\Handler\StreamHandler->createDir('/var/log/libreb...') #1 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array) #2 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(611): Monolog\Logger->addRecord(200, '[User= ()] Use...', Array) #4 /server_directory/website_folder/lib/Common/Logging/Log.php(82): Monolog\Logger->info('[User= ()] Use...') #5 /server_directory/website_folder/lib/Application/Authentication/Authentication.php(100): Log::Debug('User: %s, was v...', Array, true) #6 /server_directory/website_folder/lib/Application/Authentication/WebAuthentication.php(96): Authentication->Validate('user@websit...', 'userPasswor...') #7 /server_directory/website_folder/Presenters/LoginPresenter.php(135): WebAuthentication->Validate('user@websit...', 'userPasswor...') #8 /server_directory/website_folder/Pages/LoginPage.php(210): LoginPresenter->Login() #9 /server_directory/website_folder/Web/index.php(15): LoginPage->Login() #10 {main}UnexpectedValueException: There is no existing directory at "/var/log/librebooking/log" and it could not be created: Permission denied in /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:216 Stack trace: #0 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(135): Monolog\Handler\StreamHandler->createDir('/var/log/libreb...') #1 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array) #2 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /server_directory/website_folder/vendor/monolog/monolog/src/Monolog/Logger.php(611): Monolog\Logger->addRecord(200, '[User= ()] Log...', Array) #4 /server_directory/website_folder/lib/Common/Logging/Log.php(82): Monolog\Logger->info('[User= ()] Log...') #5 /server_directory/website_folder/lib/Application/Authentication/Authentication.php(106): Log::Debug('Logging in with...', Array) #6 /server_directory/website_folder/lib/Application/Authentication/WebAuthentication.php(106): Authentication->Login('user@websit...', Object(WebLoginContext)) #7 /server_directory/website_folder/Presenters/LoginPresenter.php(137): WebAuthentication->Login('user@websit...', Object(WebLoginContext)) #8 /server_directory/website_folder/Pages/LoginPage.php(210): LoginPresenter->Login() #9 /server_directory/website_folder/Web/index.php(15): LoginPage->Login() #10 {main}`

Thank you.

Best regards

**Comment by F0r3n5iC-Sw33t13** [comment]
Hi! 

I think the problem is the following:
There is no existing directory at "/var/log/librebooking/log" and it could not be created: Permission denied in

Can you make a folder? And do you have read and write permission?

**Comment by treborin** [comment]
Hi @RadioStars , @wfGhgATv ,

You should check your config file and set the correct value:

 * Error logging
 */
$conf['settings']['logging']['folder'] = '/var/log/librebooking/log'; //Absolute path to folder were the log will be written, writing permissions to the folder are required


The folder '/var/log/librebooking/log' is just an example, and you need to replace it with the correct one in your own case, depending on your server

**Comment by wfGhgATv** [comment]
Hi @treborin ,
_For my part, I had corrected it on my own._
Thank you for your reply.
Best regards,
