### ISSUE TITLE
Still having LDAP issues

### ISSUE THREAD

**Issue by michael-harman** [LibreBooking/app#238]
Latest release did not resolve LDAP issues.  Let me know if there's anything you all can think of, thanks!

PHP 8, MYSQL 8, APACHE

Once enabling LDAP it just displays "unknown error."  This LDAP config is confirmed working on the php7 version of librebooking.

[2023-09-26T19:31:18.710976+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:18.919095+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:19.333218+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:19.530212+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:19.697208+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:20.000199+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:20.193484+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:20.516215+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:20.717217+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.078928+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.245228+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.419255+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.597408+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.781243+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:21.961166+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:22.329151+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:22.495265+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:22.702178+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []
[2023-09-26T19:31:23.069386+00:00] app.INFO: [User=  ()] Loading plugin. Type=Authentication, Plugin=Ldap [File=/var/www/html/lib/Common/PluginManager.php,Line=184] [] []

**Comment by michael-harman** [comment]
Getting this apache error:

[Tue Sep 26 20:35:46.258237 2023] [php:notice] [pid 15840] [client 10.201.22.120:36563] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(mysqli_sql_exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(mysqli_sql_exception))\n, referer: http://10.5.0.186/Web/index.php
[Tue Sep 26 20:35:47.478911 2023] [php:notice] [pid 15841] [client 10.201.22.120:36565] Error: mysqli_sql_exception: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' in /var/www/html/lib/Database/MySQL/MySqlConnection.php:72\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(72): mysqli_query()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(126): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://10.5.0.186/Web/index.php
[Tue Sep 26 20:35:47.478938 2023] [php:notice] [pid 15841] [client 10.201.22.120:36565] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(mysqli_sql_exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(mysqli_sql_exception))\n, referer: http://10.5.0.186/Web/index.php
root@librebooking:/var/www/html/config# nano /etc/mysql/mysql.conf.d/mysqld.cnf

**Comment by michael-harman** [comment]
So I fixed it by removing NO_AUTO_CREATE_USER from /var/www/html/lib/Database/MySQL/MySqlConnection.php

Lines 72 and 94
