### ISSUE TITLE
Gone through install and site doesnt load? Getting Undefined array key error?

### ISSUE THREAD

**Issue by mckenziedave** [LibreBooking/app#284]
Hey so i have gone through the installation instructions, created the db manually imported the full install (this all went fine no errors)

However when trying to load the site where its hosted (/web directory) I'm just getting a 505 page? Checking the /web error logs i get this:

[21-Dec-2023 10:18:01 Europe/London] PHP Warning:  Undefined array key "librebooking" in /home/mckenrau/public_html/client_files/vf-hrPortal/lib/Config/Configuration.php on line 128
[21-Dec-2023 10:18:01 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function GetSectionKey() on null in /home/mckenrau/public_html/client_files/vf-hrPortal/lib/Config/Configuration.php:133
Stack trace:
#0 /home/mckenrau/public_html/client_files/vf-hrPortal/lib/Common/Logging/Log.php(94): Configuration->GetSectionKey()
#1 /home/mckenrau/public_html/client_files/vf-hrPortal/lib/Common/Logging/ExceptionHandler.php(19): Log::Error()
#2 [internal function]: ExceptionHandler::Handle()
#3 {main}
  thrown in /home/mckenrau/public_html/client_files/vf-hrPortal/lib/Config/Configuration.php on line 133

I have searched online for an answer however couldnt find one so thought id post here, anyone got any ideas? Happy to share the config file etc if needed.

(side note, if i remove the config file i get a white screen with the error saying create the config file etc... seems to be with the config added the whole things 505's?)

**Comment by daj1u06** [comment]
I've got the same issue (and others). l

ibrebooking is the default database name. I'm wanting to call mine something else (test) in order to run multiple instances for different booking systems for different uni labs and I get this in the browser when I point to http://127.0.0.1/testbooked/Web/ (my win10 test installation)

Warning: Undefined array key "test" in C:\xampp\htdocs\testbooked\lib\Config\Configuration.php on line 128

Fatal error: Uncaught Error: Call to a member function GetSectionKey() on null in C:\xampp\htdocs\testbooked\lib\Config\Configuration.php:133 Stack trace: #0 C:\xampp\htdocs\testbooked\lib\Common\Logging\Log.php(94): Configuration->GetSectionKey('logging', 'level') #1 C:\xampp\htdocs\testbooked\lib\Common\Logging\ExceptionHandler.php(19): Log::Error('Uncaught except...', Object(ParseError)) #2 [internal function]: ExceptionHandler::Handle(Object(ParseError)) #3 {main} thrown in C:\xampp\htdocs\testbooked\lib\Config\Configuration.php on line 133

**Comment by colisee** [comment]
Hi @mckenziedave ,

could you please share your config.php file?
Don't forget to XXX any visible password

**Comment by daj1u06** [comment]
this is my config.php. Every line I've edited is flagged with EDITED in the comment
<?php

mysqli_report(MYSQLI_REPORT_OFF);
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT);
//ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);

/**
 * Application configuration
 */
$conf['settings']['app.title'] = 'testbooked';			// EDITED application title
$conf['settings']['default.timezone'] = 'Europe/London';              // look up here http://php.net/manual/en/timezones.php
$conf['settings']['allow.self.registration'] = 'false';         	// EDITED if users can register themselves
$conf['settings']['admin.email'] = '*******';         // EDITED email address of admin user
$conf['settings']['admin.email.name'] = 'testbooked admin';	// EDITED name to be used in From: field when sending automatic emails
$conf['settings']['company.name'] = '';                         // name of company, if applicable
$conf['settings']['company.url'] = '';                          // URL of company, if applicable
$conf['settings']['default.page.size'] = '50';                  // number of records per page
$conf['settings']['enable.email'] = 'true';                     // global configuration to enable if any emails will be sent
$conf['settings']['default.language'] = 'en_gb';                // EDITED find your language in the lang directory
$conf['settings']['script.url'] = 'http://127.0.0.1/testbooked/Web/';   	                    // EDITED public URL to the Web directory of this instance. this is the URL that appears when you are logging in. leave http: or https: off to auto-detect
$conf['settings']['image.upload.directory'] = 'C:\xampp\htdocs\testbooked\Web\uploads\images'; // EDITED full or relative path to where images will be stored
$conf['settings']['image.upload.url'] = 'http://127.0.0.1/testbooked/Web/uploads/images';       // EDITED full or relative path to show uploaded images from
$conf['settings']['cache.templates'] = 'true';                  // true recommended, caching template files helps web pages render faster
$conf['settings']['use.local.js.libs'] = 'false';                // false recommended, delivers jQuery from Google CDN, uses less bandwidth
$conf['settings']['registration.captcha.enabled'] = 'false';     // EDITED recommended. unless using recaptcha this requires php_gd2 enabled in php.ini
$conf['settings']['registration.require.email.activation'] = 'false';		// requires enable.email = true
$conf['settings']['registration.auto.subscribe.email'] = 'false';			// requires enable.email = true
$conf['settings']['registration.notify.admin'] = 'false';		// whether the registration of a new user sends an email to the admin (ala phpScheduleIt 1.2)
$conf['settings']['inactivity.timeout'] = '10';     			// EDITED minutes before the user is automatically logged out
$conf['settings']['name.format'] = '{first} {last}';     		// display format when showing user names
$conf['settings']['css.extension.file'] = ''; 			      	// full or relative url to an additional css file to include. this can be used to override the default style
$conf['settings']['disable.password.reset'] = 'false'; 	      	// if the password reset functionality should be disabled
$conf['settings']['home.url'] = 'http://127.0.0.1/testbooked/Web'; 	      					// EDITED the url to open when the logo is clicked
$conf['settings']['logout.url'] = 'http://127.0.0.1/testbooked/Web'; 	      					// EDITED the url to be directed to after logging out
$conf['settings']['default.homepage'] = '1'; 	      			// the default homepage to use when new users register (1 = Dashboard, 2 = Schedule, 3 = My Calendar, 4 = Resource Calendar)

$conf['settings']['schedule']['use.per.user.colors'] = 'false'; 		// color reservations by user
$conf['settings']['schedule']['show.inaccessible.resources'] = 'false';  // whether or not resources that are inaccessible to the user are visible
$conf['settings']['schedule']['reservation.label'] = '{name}';    		// format for what to display on the reservation slot label.  Available properties are: {name}, {title}, {description}, {email}, {phone}, {organization}, {position}, {startdate}, {enddate} {resourcename} {participants} {invitees} {reservationAttributes}. Custom attributes can be added using att with the attribute id. For example {att1}
$conf['settings']['schedule']['hide.blocked.periods'] = 'false';    	// if blocked periods should be hidden or shown
$conf['settings']['schedule']['update.highlight.minutes'] = '0';    // if set, will show reservations as 'updated' for a certain amount of time
$conf['settings']['schedule']['show.week.numbers'] = 'false';
/**
 * ical integration configuration
 */
$conf['settings']['ics']['subscription.key'] = '';              // must be set to allow webcal subscriptions
$conf['settings']['ics']['future.days'] = '30';
$conf['settings']['ics']['past.days'] = '0';
/**
 * Privacy configuration
 */
$conf['settings']['privacy']['view.schedules'] = 'false';       			// EDITED if unauthenticated users can view schedules
$conf['settings']['privacy']['view.reservations'] = 'false';    			// if unauthenticated users can view reservations
$conf['settings']['privacy']['hide.user.details'] = 'false';    			// if personal user details should be displayed to non-administrators
$conf['settings']['privacy']['hide.reservation.details'] = 'false';			// if reservation details should be displayed to non-administrators. options are true, false, current, future, past
$conf['settings']['privacy']['allow.guest.reservations'] = 'false';			// if reservations can be made by users without a LibreBooking account, if true this overrides schedule and resource visibility
/**
 * Reservation specific configuration
 */
$conf['settings']['reservation']['start.time.constraint'] = 'current';		// EDITED when reservations can be created or edited. options are future, current, none
$conf['settings']['reservation']['updates.require.approval'] = 'false';		// if updates to previously approved reservations require approval again
$conf['settings']['reservation']['prevent.participation'] = 'false';		// if participation and invitation options should be removed
$conf['settings']['reservation']['prevent.recurrence'] = 'false';			// if recurring reservations are disabled for non-administrators
$conf['settings']['reservation']['enable.reminders'] = 'false';				// if reminders are enabled. this requires email to be enabled and the reminder job to be configured
$conf['settings']['reservation']['allow.guest.participation'] = 'false';
$conf['settings']['reservation']['allow.wait.list'] = 'false';
$conf['settings']['reservation']['checkin.minutes.prior'] = '5';
$conf['settings']['reservation']['default.start.reminder'] = '';			// the default start reservation reminder. format is ## interval. for example, 10 minutes, 2 hours, 6 days.
$conf['settings']['reservation']['default.end.reminder'] = '';				// the default end reservation reminder. format is ## interval. for example, 10 minutes, 2 hours, 6 days.
$conf['settings']['reservation']['title.required'] = 'false';
$conf['settings']['reservation']['description.required'] = 'false';
$conf['settings']['reservation']['checkin.admin.only'] = 'false';			// restrict check-in to administrators only
$conf['settings']['reservation']['checkout.admin.only'] = 'false';			// restrict check-out to administrators only
/**
 * Email notification configuration
 */
$conf['settings']['reservation.notify']['resource.admin.add'] = 'false';
$conf['settings']['reservation.notify']['resource.admin.update'] = 'false';
$conf['settings']['reservation.notify']['resource.admin.delete'] = 'false';
$conf['settings']['reservation.notify']['resource.admin.approval'] = 'false';
$conf['settings']['reservation.notify']['application.admin.add'] = 'false';
$conf['settings']['reservation.notify']['application.admin.update'] = 'false';
$conf['settings']['reservation.notify']['application.admin.delete'] = 'false';
$conf['settings']['reservation.notify']['application.admin.approval'] = 'false';
$conf['settings']['reservation.notify']['group.admin.add'] = 'false';
$conf['settings']['reservation.notify']['group.admin.update'] = 'false';
$conf['settings']['reservation.notify']['group.admin.delete'] = 'false';
$conf['settings']['reservation.notify']['group.admin.approval'] = 'false';
/**
 * File upload configuration
 */
$conf['settings']['uploads']['enable.reservation.attachments'] = 'false'; 	// if reservation attachments can be uploaded
$conf['settings']['uploads']['reservation.attachment.path'] = 'C:\xampp\htdocs\testbooked\Web\uploads\reservation'; 	// EDITED full or relative (to the root of your installation) filesystem path to store reservation attachments
$conf['settings']['uploads']['reservation.attachment.extensions'] = 'txt,jpg,gif,png,doc,docx,pdf,xls,xlsx,ppt,pptx,csv'; 	// comma separated list of file extensions that users are allowed to attach. leave empty to allow all extensions
/**
 * Database configuration
 */
$conf['settings']['database']['type'] = 'mysql';
$conf['settings']['database']['user'] = 'root';        // EDITED database user with permission to the test database
$conf['settings']['database']['password'] = '*****************'; // EDITED 
$conf['settings']['database']['hostspec'] = '127.0.0.1';        // ip, dns or named pipe
$conf['settings']['database']['name'] = 'test'; // EDITED
/**
 * Mail server configuration
 */
$conf['settings']['phpmailer']['mailer'] = 'smtp';              // options are 'mail', 'smtp' or 'sendmail'
$conf['settings']['phpmailer']['smtp.host'] = '';               // 'smtp.company.com'
$conf['settings']['phpmailer']['smtp.port'] = '25';
$conf['settings']['phpmailer']['smtp.secure'] = '';             // options are '', 'ssl' or 'tls'
$conf['settings']['phpmailer']['smtp.auth'] = 'true';           // options are 'true' or 'false'
$conf['settings']['phpmailer']['smtp.username'] = '';
$conf['settings']['phpmailer']['smtp.password'] = '';
$conf['settings']['phpmailer']['sendmail.path'] = '/usr/sbin/sendmail';
$conf['settings']['phpmailer']['smtp.debug'] = 'false';
/**
 * Plugin configuration.  For more on plugins, see readme_installation.html
 */
$conf['settings']['plugins']['Authentication'] = '';
$conf['settings']['plugins']['Authorization'] = '';
$conf['settings']['plugins']['Permission'] = '';
$conf['settings']['plugins']['PostRegistration'] = '';
$conf['settings']['plugins']['PreReservation'] = '';
$conf['settings']['plugins']['PostReservation'] = '';
/**
 * Installation settings
 */
$conf['settings']['install.password'] = '********'; // EDITED
/**
 * Pages
 */
$conf['settings']['pages']['enable.configuration'] = 'true';
/**
 * API
 */
$conf['settings']['api']['enabled'] = 'false';
$conf['settings']['api']['allow.self.registration'] = 'false';
/**
 * ReCaptcha
 */
$conf['settings']['recaptcha']['enabled'] = 'false';
$conf['settings']['recaptcha']['public.key'] = '';
$conf['settings']['recaptcha']['private.key'] = '';
/**
 * Email
 */
$conf['settings']['email']['default.from.address'] = '';
$conf['settings']['email']['default.from.name'] = '';
/**
 * Reports
 */
$conf['settings']['reports']['allow.all.users'] = 'false';
/**
 * Account Password Rules
 */
$conf['settings']['password']['minimum.letters'] = '8'; //EDITED
$conf['settings']['password']['minimum.numbers'] = '1'; //EDITED
$conf['settings']['password']['upper.and.lower'] = 'true'; //EDITED
/**
 * Label display settings
 */
$conf['settings']['reservation.labels']['ics.summary'] = '{title}';
$conf['settings']['reservation.labels']['ics.my.summary'] = '{title}';
$conf['settings']['reservation.labels']['rss.description'] = '<div><span>Start</span> {startdate}</div><div><span>End</span> {enddate}</div><div><span>Organizer</span> {name}</div><div><span>Description</span> {description}</div>';
$conf['settings']['reservation.labels']['my.calendar'] = '{resourcename} {title}';
$conf['settings']['reservation.labels']['resource.calendar'] = '{name}';
$conf['settings']['reservation.labels']['reservation.popup'] = ''; // Format for what to display in reservation popups. Possible values: {name} {dates} {title} {resources} {participants} {accessories} {description} {attributes} {pending} {duration}. Custom attributes can be added using att with the attribute id. For example {att1}
/**
 * Security header settings
 */
$conf['settings']['security']['security.headers'] = 'false'; // Enable the following options
$conf['settings']['security']['security.strict-transport'] = 'true';
$conf['settings']['security']['security.x-frame'] = 'deny';
$conf['settings']['security']['security.x-xss'] = '1; mode=block';
$conf['settings']['security']['security.x-content-type'] = 'nosniff';
$conf['settings']['security']['security.content-security-policy'] = ""; // Requires careful tuning (know what your doing)
/**
 * Google Analytics settings
 */
$conf['settings']['google.analytics']['tracking.id'] = ''; // if set, Google Analytics tracking code will be added to every page in LibreBooking

$conf['settings']['authentication']['allow.facebook.login'] = 'false';
$conf['settings']['authentication']['allow.google.login'] = 'false';
$conf['settings']['authentication']['required.email.domains'] = '';
$conf['settings']['authentication']['hide.booked.login.prompt'] = 'false';
$conf['settings']['authentication']['captcha.on.login'] = 'false';
/**
 * Credits
 */
$conf['settings']['credits']['enabled'] = 'false';
$conf['settings']['credits']['allow.purchase'] = 'false';
/**
 * Slack integration
 */
$conf['settings']['slack']['token'] = '';
/**
 * Tablet view
 */
$conf['settings']['tablet.view']['allow.guest.reservations'] = 'false';
$conf['settings']['tablet.view']['auto.suggest.emails'] = 'false';
/**
 * Registration
 */
$conf['settings']['registration']['require.phone'] = 'false';
$conf['settings']['registration']['require.position'] = 'false';
$conf['settings']['registration']['require.organization'] = 'false';
/**
 * Error logging
 */
$conf['settings']['logging']['folder'] = 'C:\xampp\htdocs\testbooked\log'; // EDITED Absolute path to folder were the log will be written, writing permissions to the folder are required
$conf['settings']['logging']['level'] = 'debug'; // EDITED Set to none disable logs, error to only log errors or debug to log all messages to the app.log file 
$conf['settings']['logging']['sql'] = 'false'; //Set to true no enable the creation of and sql.log file

**Comment by colisee** [comment]
Hi @daj1u06 ,

it looks like your `config.php`file is truncated...
Please, compare your `config.php` file with the sample `config.dist.php`file.

If it is indeed truncated, then I would recommend you re-create your `config.php`file from `config.dist.php` and change the value of the fields that are relevant to you.

**Comment by daj1u06** [comment]
Thanks, checked and wasn't truncated, just it didn't all insert in when pasted into the box (size limit?). I found 2 typos in my config.php file and when corrected allowed Web/install tolaunch and with some other tweaking, I'm up and running.

**Comment by iborby** [comment]
Having the same problem. I've tried to go trough installation on AWS lightsail LAMP stack and a clean EC2 AMI where I have installed php, mariadb, ecc.. The only thing I can running is a blank page.  Attached my [config.php](https://github.com/LibreBooking/app/files/13847431/config.php.txt).

**Comment by colisee** [comment]
Hi @iborby,

I think your statement  $conf['settings']['script.url'] = '/var/www/html/' is incorrect... I believe you should define a url (ex: www.acme.com).

**Comment by iborby** [comment]
I've updated it with: 'http://serverip/Web' as per index.php commented echo, tried also 'http://serverip/app/Web'. To be sure I have also tried db connection with mysql -h 127.0.0.1 -u username -D dbname -p and I'm able to se data in the tables so I assume it's not a DB connection issue.
