### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by Liliputech** [LibreBooking/app#312]
git clone repository, tried to docker-compose up, got this error:
`Fatal error: Uncaught Error: Class "Smarty" not found in /var/www/librebooking/lib/Email/SmartyEmail.php:9 Stack trace: #0 /var/www/librebooking/lib/Email/namespace.php(7): require_once() #1 /var/www/librebooking/lib/Email/Messages/AccountCreationEmail.php(3): require_once('/var/www/libreb...') #2 /var/www/librebooking/Domain/Access/UserRepository.php(7): require_once('/var/www/libreb...') #3 /var/www/librebooking/Domain/Access/namespace.php(13): require_once('/var/www/libreb...') #4 /var/www/librebooking/lib/Common/Validators/TermsOfServiceValidator.php(3): require_once('/var/www/libreb...') #5 /var/www/librebooking/lib/Common/Validators/namespace.php(20): require_once('/var/www/libreb...') #6 /var/www/librebooking/lib/Common/SmartyPage.php(8): require_once('/var/www/libreb...') #7 /var/www/librebooking/lib/Common/namespace.php(5): require_once('/var/www/libreb...') #8 /var/www/librebooking/Pages/Page.php(10): require_once('/var/www/libreb...') #9 /var/www/librebooking/Pages/LoginPage.php(8): require_once('/var/www/libreb...') #10 /var/www/librebooking/Web/index.php(9): require_once('/var/www/libreb...') #11 {main} thrown in /var/www/librebooking/lib/Email/SmartyEmail.php on line 9`

**Comment by colisee** [comment]
Hi @Liliputech ,

I believe that the Dockerfile file found in the librebooking/app repository is not actively maintained and no longer in sync with version 2.8.6.1

May I suggest you have a look at the librebooking/docker repository instead?
