### ISSUE TITLE
API authentication issue when enable Active Directory authentication plugin

### ISSUE THREAD

**Issue by sarkhanabbasov** [LibreBooking/app#317]
Active Directory authentication works but API authentication error fails with error below.  API works only when disable Active Directory plugin.

<html>

<head>
    <title>Slim Application Error</title>
    <style>
        body {
            margin: 0;
            padding: 30px;
            font: 12px/1.5 Helvetica, Arial, Verdana, sans-serif;
        }

        h1 {
            margin: 0;
            font-size: 48px;
            font-weight: normal;
            line-height: 48px;
        }

        strong {
            display: inline-block;
            width: 65px;
        }
    </style>
</head>

<body>
    <h1>Slim Application Error</h1>
    <p>The application could not run because of the following error:</p>
    <h2>Details</h2>
    <div><strong>Code:</strong> 2</div>
    <div><strong>Message:</strong> Undefined array key "REMOTE_USER"</div>
    <div><strong>File:</strong> /var/www/html/plugins/Authentication/ActiveDirectory/adLDAP.php</div>
    <div><strong>Line:</strong> 682</div>
    <h2>Trace</h2>
    <pre>#0 /var/www/html/plugins/Authentication/ActiveDirectory/adLDAP.php(682): Slim\Slim::handleErrors()
#1 /var/www/html/plugins/Authentication/ActiveDirectory/adLDAP.php(632): adLDAP->connect()
#2 /var/www/html/plugins/Authentication/ActiveDirectory/AdLdapWrapper.php(38): adLDAP->__construct()
#3 /var/www/html/plugins/Authentication/ActiveDirectory/ActiveDirectory.php(88): AdLdapWrapper->Connect()
#4 /var/www/html/lib/Application/Authentication/WebServiceAuthentication.php(53): ActiveDirectory->Validate()
#5 /var/www/html/WebServices/AuthenticationWebService.php(38): WebServiceAuthentication->Validate()
#6 [internal function]: AuthenticationWebService->Authenticate()
#7 /var/www/html/lib/external/Slim/Router.php(200): call_user_func_array()
#8 /var/www/html/lib/external/Slim/Slim.php(1218): Slim\Router->dispatch()
#9 /var/www/html/lib/external/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#10 /var/www/html/lib/external/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#11 /var/www/html/lib/external/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /var/www/html/lib/external/Slim/Slim.php(1167): Slim\Middleware\PrettyExceptions->call()
#13 /var/www/html/Web/Services/index.php(69): Slim\Slim->run()
#14 {main}</pre>
</body>

</html>

**Comment by JensWendt** [comment]
*bump

We also tried out the API calls for the first time and ran into issues. 
After implementing PR #422 manually we ran into the same error as described above.
We are running version 2.8.6.1
Any help/pointers would be valuable.
I only found [this](https://github.com/dokuwiki/dokuwiki/issues/4215#issuecomment-1951351534), which I am not able to judge if it might be helpful, or how to resolve this.
PS: We have `use.sso` for the ActiveDirectory plugin config as `false`
