### ISSUE TITLE
app.ERROR: [User=me@here.com] Uncaught exception: Error: Call to a member function FullName() on string in C:\wamp64\www\resa2024\tpl_c\..._0.file.ReservationCreated.tpl.php:128

### ISSUE THREAD

**Issue by pfs007** [LibreBooking/app#337]
Hi,

I get this error

`app.ERROR: [User=me@here.com] Uncaught exception: Error: Call to a member function FullName() on string in C:\wamp64\www\resa2024\tpl_c\..._0.file.ReservationCreated.tpl.php:128`

This problem only appears when, **while logged in as Admin**, I reserve a slot **on behalf of someone else** with one or more participants. It appears every time and I have an "Unknown error" on the screen.

![2024-05-06 10 32 15](https://github.com/LibreBooking/app/assets/96306498/1882a7b3-44f7-4a77-93b0-46ac60248b08)

The reservation is however well recorded, and the emails correctly sent.
Everything works well if I do not change the owner of the slot when reserving a slot.

Obviously, the error **does not occur** when I set false to $conf['settings']['enable.email'] = 'false'.

It happens on my online server on Ionos, and also on my local Wamp server.
It happens in standard English version and in French version.
I installed version 2.8.6.1 of LibreBooking.
Both run PHP 8.1 or higher, and MySql 8.0 (Ionos) 8.3 (Wamp).

Here is the whole error message.

`[2024-05-06T06:13:10.987321+00:00] app.ERROR: [User=me@here.com] Uncaught exception: Error: Call to a member function FullName() on string in C:\wamp64\www\resa2024\tpl_c\a14f77c1c37bbe19f7b3f972bbabc8517fb9ace3_0.file.ReservationCreated.tpl.php:128 Stack trace: #0 C:\wamp64\www\resa2024\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_663874f6c2bd76_88176831(Object(Smarty_Internal_Template)) #1 C:\wamp64\www\resa2024\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) #2 C:\wamp64\www\resa2024\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) #3 C:\wamp64\www\resa2024\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) #4 C:\wamp64\www\resa2024\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0) #5 C:\wamp64\www\resa2024\lib\Common\SmartyPage.php(125): Smarty_Internal_TemplateBase->fetch('ReservationCrea...') #6 C:\wamp64\www\resa2024\lib\Email\EmailMessage.php(40): SmartyPage->FetchLocalized('ReservationCrea...') #7 C:\wamp64\www\resa2024\lib\Email\Messages\ReservationEmailMessage.php(79): EmailMessage->FetchTemplate('ReservationCrea...') #8 C:\wamp64\www\resa2024\lib\Email\EmailService.php(40): ReservationEmailMessage->Body() #9 C:\wamp64\www\resa2024\lib\Application\Reservation\Notification\OwnerEmailNotification.php(41): EmailService->Send(Object(ReservationCreatedEmail)) #10 C:\wamp64\www\resa2024\lib\Application\Reservation\Notification\IReservationNotificationService.php(39): OwnerEmailNotification->Notify(Object(ReservationSeries)) #11 C:\wamp64\www\resa2024\lib\Application\Reservation\ReservationHandler.php(103): ReservationNotificationService->Notify(Object(ReservationSeries)) #12 C:\wamp64\www\resa2024\Presenters\Reservation\ReservationSavePresenter.php(146): ReservationHandler->Handle(Object(ReservationSeries), Object(ReservationSavePage)) #13 C:\wamp64\www\resa2024\Pages\Ajax\ReservationSavePage.php(165): ReservationSavePresenter->HandleReservation(Object(ReservationSeries)) #14 C:\wamp64\www\resa2024\Web\ajax\reservation_save.php(8): ReservationSavePage->PageLoad() #15 {main} [File=C:\wamp64\www\resa2024\lib\Common\Logging\ExceptionHandler.php,Line=19] [] []`

Thank you for any help.

Have a good day.

PFS

**Comment by pfs007** [comment]
Hi,
I found the mistake, I did an error coding on a former version of LibreBooking that used to work but not any more.
Sorry for this wrong issue.
Regards.
PFS
