### ISSUE TITLE
get_magic_quotes_gpc error on api authentication

### ISSUE THREAD

**Issue by marloesim** [LibreBooking/app#77]
Hi,

I am trying to use the API to fetch bookings. The authentication request returns an error.

`Code: 8192`
`Message: Function get_magic_quotes_gpc() is deprecated`

`Trace`
`#0 https://mylocalpath.nl/lib/external/Slim/Http/Util.php(59): Slim\Slim::handleErrors(8192, 'Function get_ma...', 'https://mylocalpath.nl....', 59, Array)`
`#1 https://mylocalpath.nl/lib/external/Slim/Http/Request.php(242): Slim\Http\Util::stripSlashesIfMagicQuotes(Array)`
`#2 https://mylocalpath.nl/lib/external/Slim/Middleware/MethodOverride.php(88): Slim\Http\Request->post('_METHOD')`
`#3 https://mylocalpath.nl/lib/external/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()`
`#4 https://mylocalpath.nl/lib/external/Slim/Slim.php(1167): Slim\Middleware\PrettyExceptions->call()`
`#5 https://mylocalpath.nl/Web/Services/index.php(67): Slim\Slim->run()`
`#6 {main}`

Since get_magic_quotes_gpc is deprecated I would think this function should not be called?
How do I get the authentication with the API working?

**Comment by qlux** [comment]
In the meantime you can ignore the deprecated warnings by replacing the first line of the `config.php`:
```
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);
```
That's what the Slim community recommends

**Comment by JohnVillalovos** [comment]
This issue seems stale. Closing. Feel free to reopen if desired.
