### ISSUE TITLE
error There was an error executing your query

### ISSUE THREAD

**Issue by cvanh** [LibreBooking/app#85]
working on a fresh install of bookedscheduler and i am getting the same error over and over and over again. does anyone have some pointers on what is going wrong or what i can check?

```
2021-11-10T12:16:43+01:00 [172569] ERROR default - [User=  ()] Error executing MySQL query  [File=/var/www/html/BookedScheduler/lib/Database/MySQL/MySqlConnection.php,Line=112]
2021-11-10T12:16:43+01:00 [172569] ERROR default - [User=  ()] Uncaught exception: Exception: There was an error executing your query\n in /var/www/html/BookedScheduler/lib/Database/MySQL/MySqlConnection.php:115
Stack trace:
#0 /var/www/html/BookedScheduler/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()
#1 /var/www/html/BookedScheduler/lib/Database/Database.php(27): MySqlConnection->Query()
#2 /var/www/html/BookedScheduler/Domain/Access/AnnouncementRepository.php(11): Database->Query()
#3 /var/www/html/BookedScheduler/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()
#4 /var/www/html/BookedScheduler/Pages/LoginPage.php(124): LoginPresenter->PageLoad()
#5 /var/www/html/BookedScheduler/Web/index.php(22): LoginPage->PageLoad()
#6 {main} [File=/var/www/html/BookedScheduler/lib/Common/Logging/ExceptionHandler.php,Line=19]
```

some details
php version; PHP 7.4.25
apache version: Apache/2.4.41 (Ubuntu)

**Comment by cvanh** [comment]
as it turns out it was a bug on the dev branch so we switched to the master branch and now everything works

**Comment by effgarces** [comment]
If have some more information about this I would appreciate it, I have one or two dev installs that seem to be working fine, so if more info, like que sql log it would help squash this "bug" from the dev version.

**Comment by JohnVillalovos** [comment]
This issue seems stale. Closing. Feel free to reopen if desired.
